### PR TITLE
feat: display connection status on device list

### PR DESCRIPTION
**Pull request by pbogut**
Not sure if you fancy that, if not just close the PR.

Adds icon on device list next to connected devices.

### CODE REVIEW

**Comment by Layerex** [comment]
It would be better to add a command line argument or an environment variable to enable this, since not everyone uses icon fonts. Also, which font do I need to test it?

**Comment by pbogut** [comment]
Fair point. I've created it for myself and added pull request in case you are interested in something like that (or any user is).

I do agree that for the general use it would be better to have argument or environment variable.
I've updated the code to handle both so now you can use it like this:

```
BT_CONNECTED_ICON="!" dmenu-bluetooth
````
or
```
dmenu-bluetooth --connected-icon "?"
```

If you prefer one over another let me know, I'm happy to change it.

**Comment by Layerex** [comment]
Please add an option to use a default icon (if user doesn't pass an icon to `--connected-icon`). I don't know, how to specify this unambigously using an environment variable, so command line argument is preferable there, I guess.

**Comment by pbogut** [comment]
Sure, I've added that option and removed environment variable as there is no need for two ways to set up one thing.

Default icon is the same as the one used for showing power on status  in `--status`.

```
dmenu-bluetooth --connected-icon
```
bt-icon

**Comment by Layerex** [comment]
Thanks for contribution!

**Pull request merged**
